---
name: Application CI Pipeline on Push
env:
  CONTAINER_IMAGE: pramanick1984/sample2
on:
  push:
    branches: [master]
jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag docker image
      run: |
        docker build . -t ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::7}

    - name: Publish docker image to dockerhub
      run: docker push ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::7}
